apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: containerworkshopvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "containerworkshopvault"  
    objects:  |
      array:
        - |
          objectName: connectionstrings--leaderboardcontext
          objectType: secret
          objectVersion: ""
    resourceGroup: "ContainerWorkshop"                      
    subscriptionId: "6eb94a2c-34ac-45db-911f-c21438b4939c"  # [REQUIRED] the subscription ID of the key vault, use az account show
    tenantId: "9c872e88-865c-4c4e-b258-0934b470991d"        # [REQUIRED] the tenant ID of the key vault
